services:
  - type: web
    name: tcc-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --worker-class sync --worker-connections 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
